### ISSUE TITLE
Source new wallpapers for R1.2 release

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-assets#1]
The [existing wallpapers](https://psiupuxa.com) do not scale well to 4K monitors due to their lower resolution.  This task is to find thematically similar wallpapers in 4K, use something other than "planetary surface" images, or use colors or patterns instead of images.

**Comment by kgilmer** [comment]
I'm really liking this with Nord: https://unsplash.com/photos/xnqVGsbXgV4

I have not been able to find a source for "planetary surface" wallpapers of sufficient fidelity and aesthetic quality and so am considering not using that theme for 1.2.  If anyone has suggestions or ideas...
![image](https://user-images.githubusercontent.com/49683/63781167-302aa580-c89e-11e9-942b-a97bcb0cc379.png)

**Comment by ahoneybun** [comment]
Images with colors and patterns may be better for scaling.

**Comment by kgilmer** [comment]
Email to hello@psiupuxa.com bounces so doesn't seem like that's actively maintained.
